import type { GitHubUser } from "../types";

export const mockUsers: GitHubUser[] = [
  {
    login: "octocat",
    name: "The Octocat",
    email: "octocat@example.com",
    type: "User",
    sponsorable: true,
    avatarUrl: "https://avatars.githubusercontent.com/u/583231?v=4",
    stats: { repositories: 120, followers: 9200, joined: "2011-01-25" },
    location: "San Francisco",
    languages: ["JavaScript", "TypeScript"],
    bio: "Mascot and sample account used for GitHub demos.",
    url: "https://github.com/octocat",
  },
  {
    login: "hanseul",
    name: "Han Seul Lee",
    email: "hanseul@example.com",
    type: "User",
    sponsorable: false,
    avatarUrl: "https://avatars.githubusercontent.com/u/1812?v=4",
    stats: { repositories: 42, followers: 1800, joined: "2019-06-12" },
    location: "Seoul",
    languages: ["TypeScript", "Rust"],
    bio: "Building developer tooling for distributed teams.",
    url: "https://github.com/hanseul",
  },
  {
    login: "dataforge",
    name: "DataForge Labs",
    email: "hello@dataforge.dev",
    type: "Organization",
    sponsorable: true,
    avatarUrl: "https://avatars.githubusercontent.com/u/552311?v=4",
    stats: { repositories: 210, followers: 12000, joined: "2014-02-11" },
    location: "Berlin",
    languages: ["Python", "Go"],
    bio: "Open data infrastructure and ETL pipelines.",
    url: "https://github.com/dataforge",
  },
  {
    login: "frontend-fox",
    name: "Mina Park",
    email: "mina@frontendfox.dev",
    type: "User",
    sponsorable: true,
    avatarUrl: "https://avatars.githubusercontent.com/u/81221?v=4",
    stats: { repositories: 87, followers: 4300, joined: "2016-08-04" },
    location: "Tokyo",
    languages: ["TypeScript", "Kotlin"],
    bio: "Design systems and DX advocate.",
    url: "https://github.com/frontend-fox",
  },
  {
    login: "devseoul",
    name: "Dev Seoul Collective",
    email: "team@devseoul.org",
    type: "Organization",
    sponsorable: false,
    avatarUrl: "https://avatars.githubusercontent.com/u/4432122?v=4",
    stats: { repositories: 65, followers: 5400, joined: "2018-10-23" },
    location: "Seoul",
    languages: ["JavaScript", "Python"],
    bio: "Community-driven OSS for civic tech in Korea.",
    url: "https://github.com/devseoul",
  },
  {
    login: "byte-sculptor",
    name: "Byte Sculptor",
    email: "hello@bytesculptor.dev",
    type: "User",
    sponsorable: false,
    avatarUrl: "https://avatars.githubusercontent.com/u/101122?v=4",
    stats: { repositories: 33, followers: 780, joined: "2021-03-18" },
    location: "Sydney",
    languages: ["Go", "Rust"],
    bio: "Edge computing hobbyist shipping side projects.",
    url: "https://github.com/byte-sculptor",
  },
  {
    login: "algorhythm",
    name: "Algo Rhythm",
    email: "contact@algorhythm.ai",
    type: "Organization",
    sponsorable: true,
    avatarUrl: "https://avatars.githubusercontent.com/u/72231?v=4",
    stats: { repositories: 154, followers: 8900, joined: "2015-12-01" },
    location: "New York",
    languages: ["Python", "Java"],
    bio: "Applied ML research group working on audio models.",
    url: "https://github.com/algorhythm",
  },
  {
    login: "orbit-labs",
    name: "Orbit Labs",
    email: "hi@orbitlabs.dev",
    type: "Organization",
    sponsorable: false,
    avatarUrl: "https://avatars.githubusercontent.com/u/1381211?v=4",
    stats: { repositories: 97, followers: 3100, joined: "2020-05-15" },
    location: "Remote",
    languages: ["TypeScript", "Swift"],
    bio: "Satellite imagery tooling and visualization.",
    url: "https://github.com/orbit-labs",
  },
  {
    login: "codestudio",
    name: "Code Studio",
    email: "team@codestudio.dev",
    type: "Organization",
    sponsorable: true,
    avatarUrl: "https://avatars.githubusercontent.com/u/71231?v=4",
    stats: { repositories: 305, followers: 19500, joined: "2012-11-19" },
    location: "London",
    languages: ["JavaScript", "PHP"],
    bio: "Digital agency shipping rapid prototypes.",
    url: "https://github.com/codestudio",
  },
  {
    login: "moonshotai",
    name: "Moonshot AI",
    email: "hello@moonshot.ai",
    type: "Organization",
    sponsorable: true,
    avatarUrl: "https://avatars.githubusercontent.com/u/800330?v=4",
    stats: { repositories: 76, followers: 7600, joined: "2017-07-07" },
    location: "Singapore",
    languages: ["Python", "TypeScript"],
    bio: "Foundation models for recommendation systems.",
    url: "https://github.com/moonshotai",
  },
  {
    login: "tiger-ops",
    name: "Tiger Ops",
    email: "ops@tiger.dev",
    type: "User",
    sponsorable: false,
    avatarUrl: "https://avatars.githubusercontent.com/u/400120?v=4",
    stats: { repositories: 58, followers: 2300, joined: "2018-02-02" },
    location: "Busan",
    languages: ["Go", "Rust"],
    bio: "Platform engineering and SRE content.",
    url: "https://github.com/tiger-ops",
  },
  {
    login: "cloud-arch",
    name: "Cloud Architecture Guild",
    email: "guild@cloudarch.dev",
    type: "Organization",
    sponsorable: false,
    avatarUrl: "https://avatars.githubusercontent.com/u/1091231?v=4",
    stats: { repositories: 188, followers: 15100, joined: "2013-09-30" },
    location: "San Francisco",
    languages: ["Go", "C#"],
    bio: "Reference designs for distributed systems.",
    url: "https://github.com/cloud-arch",
  },
  {
    login: "hybrid-stack",
    name: "Eun Ji Kim",
    email: "eunji@hybridstack.dev",
    type: "User",
    sponsorable: true,
    avatarUrl: "https://avatars.githubusercontent.com/u/665432?v=4",
    stats: { repositories: 44, followers: 980, joined: "2022-04-10" },
    location: "Seoul",
    languages: ["TypeScript", "Swift"],
    bio: "Hybrid mobile + web experiences.",
    url: "https://github.com/hybrid-stack",
  },
  {
    login: "kawatech",
    name: "Kawa Tech",
    email: "contact@kawatech.jp",
    type: "Organization",
    sponsorable: false,
    avatarUrl: "https://avatars.githubusercontent.com/u/923331?v=4",
    stats: { repositories: 54, followers: 2700, joined: "2019-01-14" },
    location: "Osaka",
    languages: ["Java", "Kotlin"],
    bio: "Android platform specialists.",
    url: "https://github.com/kawatech",
  },
  {
    login: "lumen-labs",
    name: "Lumen Labs",
    email: "labs@lumen.dev",
    type: "Organization",
    sponsorable: true,
    avatarUrl: "https://avatars.githubusercontent.com/u/51131?v=4",
    stats: { repositories: 120, followers: 6400, joined: "2016-01-08" },
    location: "Berlin",
    languages: ["Rust", "C++"],
    bio: "Graphics & rendering R&D team.",
    url: "https://github.com/lumen-labs",
  },
  {
    login: "pixelcraft",
    name: "Pixel Craft",
    email: "team@pixelcraft.studio",
    type: "Organization",
    sponsorable: false,
    avatarUrl: "https://avatars.githubusercontent.com/u/400921?v=4",
    stats: { repositories: 92, followers: 5200, joined: "2015-05-05" },
    location: "New York",
    languages: ["TypeScript", "Swift"],
    bio: "Immersive web experiences and WebGL demos.",
    url: "https://github.com/pixelcraft",
  },
  {
    login: "solis-dev",
    name: "Solis Dev",
    email: "solis@studio.dev",
    type: "User",
    sponsorable: true,
    avatarUrl: "https://avatars.githubusercontent.com/u/557812?v=4",
    stats: { repositories: 27, followers: 640, joined: "2020-10-01" },
    location: "Berlin",
    languages: ["TypeScript", "Python"],
    bio: "Automations and small SaaS experiments.",
    url: "https://github.com/solis-dev",
  },
  {
    login: "zen-flow",
    name: "Zen Flow",
    email: "zen@flow.studio",
    type: "User",
    sponsorable: false,
    avatarUrl: "https://avatars.githubusercontent.com/u/1235125?v=4",
    stats: { repositories: 68, followers: 3100, joined: "2014-03-03" },
    location: "London",
    languages: ["JavaScript", "Ruby"],
    bio: "Sustainable web tech and mindful dev.",
    url: "https://github.com/zen-flow",
  },
  {
    login: "deepsea-ai",
    name: "DeepSea AI",
    email: "hello@deepsea.ai",
    type: "Organization",
    sponsorable: true,
    avatarUrl: "https://avatars.githubusercontent.com/u/495812?v=4",
    stats: { repositories: 142, followers: 11200, joined: "2015-09-18" },
    location: "Singapore",
    languages: ["Python", "Go"],
    bio: "Marine robotics perception stack.",
    url: "https://github.com/deepsea-ai",
  },
  {
    login: "northern-lights",
    name: "Northern Lights",
    email: "contact@nlights.io",
    type: "Organization",
    sponsorable: false,
    avatarUrl: "https://avatars.githubusercontent.com/u/755331?v=4",
    stats: { repositories: 48, followers: 2500, joined: "2021-11-11" },
    location: "Remote",
    languages: ["Rust", "Go"],
    bio: "Distributed ledger research collective.",
    url: "https://github.com/northern-lights",
  },
  {
    login: "cascadia-dev",
    name: "Cascadia Dev",
    email: "hi@cascadiadev.com",
    type: "User",
    sponsorable: false,
    avatarUrl: "https://avatars.githubusercontent.com/u/991123?v=4",
    stats: { repositories: 35, followers: 1250, joined: "2019-09-09" },
    location: "Seattle",
    languages: ["TypeScript", "Python"],
    bio: "Cloud-native starter kits and templates.",
    url: "https://github.com/cascadia-dev",
  },
];
